### ISSUE TITLE
Small edit. 

### ISSUE THREAD

**Issue by Varietyy** [Yemasthui/basicBot#12]
"voteratio": "/me [@%%NAME%%] @%%USERNAME%% ~ woots: ' + %%WOOT%% + ', mehs: %%MEHS%%, ratio (w/m): %%RATIO%%.",

Doesn't need ' + and + ' for the %%WOOT%% :)

**Comment by Benzi** [comment]
@Varietyy sorry about that. Just a silly typo, but it's fixed now.
