### ISSUE TITLE
!DC abuse

### ISSUE THREAD

**Issue by GryphonEDM** [Yemasthui/basicBot#21]
When a user uses !DC after it seems leaving the room for around maybe 15s but less than 30s and return it places them at #1 spot even if they were not there.

**Comment by Benzi** [comment]
You might want to set the maximum DC time to something shorter, like 10 minutes. This should reduce the level of DC abuse. (Temporary solution until it's fixed.)

**Comment by Dazzuh** [comment]
`if (newPosition <= 0) newPosition = 1;`

Isn't this the main reason people can abuse !dc?

if the DJ leaves with a few seconds left of their song, they can rejoin and  !dc back to pos 1.

**Comment by Hunchmun** [comment]
Yeah, I'd agree that -1 should probably change it to null or whatever value is representative of not being in the waitlist

**Comment by Benzi** [comment]
This https://github.com/Yemasthui/basicBot/commit/5ad61101528895e42578e5f24d44ab70c5957ddb should resolve it.
