### ISSUE TITLE
Woot/Grab/Meh Calculate to skip

### ISSUE THREAD

**Issue by Exuviax** [Yemasthui/basicBot#22]
Not sure why this isn't coded into Plug.dj itself, but I would like for a way to be able to do a command that will skip songs once they reach a certain number of meh's: Example
!meh 10
[@Exuviax] I will now skip songs when they receive a total of 10 down-votes.

Then the bot will do math on each song, it will take the total number of Meh's and total number of Woot's and minus the Woot's from the meh's to get the total down-votes.

Say a song has 10 meh's and 7 woot's, in reality, the song has 3 down-votes (After calculation) 

Now, since I set the bot to skip the song at a total of 10 down-votes, and this song in question only has 3 after some simple math, it won't skip.

Well now the song had 32 meh's and 22 woot's, well 32 - 22 = 10 total Down-votes and now it's skipped.

I have been looking into adding it myself, but I am not super good with JS.

**Comment by Benzi** [comment]
Alright @Exuviax, I forked @Yemasthui's repo and added the voteskip feature to the bot exactly as you requested.

You can find the updated repo containing the voteskip feature [here](https://github.com/Benzi/basicBot).

### It functions as so:

- You can toggle to voteskip feature simply by typing `!togglevoteskip` in chat. (Default is OFF)

- You can change the voteskip limit by typing `!voteskip 10`. (Default is 10)
(10 is used as an example. This would would mean if the number of mehs substract the number of woots equate to 10, the song will be skipped and will also return `/me @user, your song has exceeded the maximum amount of mehs needed to skip.` in chat.

- You can also type `!voteskip` in chat to see the voteskip limit currently set. It will return something like `/me Voteskip limit is currently set to a difference of 10 mehs.` (10 being an example of course.)

That's about it.. if you have any issues, you can contact me via email benzi@email.com :v:

**Comment by Exuviax** [comment]
Thank you Benzi!
