### ISSUE TITLE
BlackList

### ISSUE THREAD

**Issue by Exuviax** [Yemasthui/basicBot#25]
How does the blacklist work exactly, and how would I add things to it locally + Remove things from it.

I don't really understand how to phraze the Json, say I want to BL this song
https://www.youtube.com/watch?v=qPG9ijzWVV4

How would it look? 

Also, say I BL a song in chat. How do I remove it?

**Comment by Benzi** [comment]
Firstly, you need to make a JSON file which will store the songs you blacklist.
> Example: op.json

You then need to add some songs to the file. This can be done either manually or by using a form which writes into the JSON file. I'll show you the basics of how to make it work to avoid any confusion.

First, make sure the JSON file is online and add the link to the **basicBot.js** file like so:

```javascript
blacklists: {
    OP: "https://example.com/op.json"
}
```

The structure of the JSON file should look like this:
```json
[
    {
        "title": "#SELFIE",
        "author": "The Chainsmokers",
        "mid": "1:kdemFfbS5H0"
    },
    {
        "title": "Battle Scars (Lyrics On Screen) Feat. Lupe Fiasco",
        "author": "Guy Sebastian",
        "mid": "1:qPG9ijzWVV4"
    }
]
```

You can find all the required information for blacklisting a song by entering `API.getMedia()` in the chrome console (Press F12 to access the console).

```
title = API.getMedia().title
author = API.getMedia().author
mid = API.getMedia().format + ":" + API.getMedia().cid
```

- Format is either `1` or `2`:
  - `1` = a YouTube video.
  - `2` = a Soundcloud track.

> You may need to reload the bot once you're made updates to your JSON file for your changes to be applied.

-

You can also blacklist a song directly in chat but the downside is that it's temporary and will be removed at the end of your session (when you close the browser your bot's running on).

This can be done by typing `!bl OP` in chat (`OP` being the name of the blacklist you so choose).

---

I would suggest hosting your JSON file on [Dropbox](https://Dropbox.com) as it's then very easy to update the JSON file manually.

I hope this was helpful,

[Benzi](https://github.com/Benzi)
