### ISSUE TITLE
!status seems to not be working

### ISSUE THREAD

**Issue by berkuhlee** [Yemasthui/basicBot#29]
also minor problem since the new update: when you type a command for the bot (such as !ping) it deletes the command and any of your text that is recent (since the new update deletes in chunks instead of individual messages).

**Comment by Benzi** [comment]
I fixed the `!status` command. It was a silly typo on my part :stuck_out_tongue:

Regarding the new plug update, yes the new chat layout stacks messages together which makes it harder to target individual messages. Unless plug.dj decides to revert back to their old chat layout (very unlikely) we're going to have to deal with this new layout.

The easier way to prevent messages to be deleted involuntarily is to simply disable chat deletion when a command is triggered. You could also break the "stack" by sending an emote (`/me msg` or `/em msg`) in chat before triggering a command.

I'll be happy to hear you guys' ideas on what you think would be the best way of dealing with this.

Benzi

**Comment by berkuhlee** [comment]
How do I disable chat deletion on commands?

**Comment by trevinwoodstock** [comment]
As long as you don't mind a little script modification, simply remove this [line](https://github.com/Yemasthui/basicBot/blob/master/basicBot.js#L1067) before you load in the script.
