### ISSUE TITLE
If you exit the page without doing !kill

### ISSUE THREAD

**Issue by Killdore21** [Yemasthui/basicBot#35]
I see that if you are not doing !kill before you exit, you can't edit the bot!

**Comment by Benzi** [comment]
Hi @Killdore21,

I don't quite understand what you mean by "edit". Do you mean editing the code or the bot settings? Could you please elaborate more on the issue?

[Benzi](http://github.com/benzi)

**Comment by Killdore21** [comment]
I mean if you runs the bot, and go out of that page (I have tryed this.), you can't for example dont edit the Website-thing. I sett'd the Website to something, and when I should edit it, i exited the page and edited. I waited, and runned the bot again.. It stills says that Website I setted there before. You get it?

-Killdore21

I am not soo good at English... Say if you dont understand me again... ;)
