### ISSUE TITLE
Copyright And Disclaimer very conflicting

### ISSUE THREAD

**Issue by nthitz** [Yemasthui/basicBot#44]
The Copyright & License say "Modifications (including forks) of the code to fit personal needs are allowed only for personal use and should refer back to the original source"

but then the disclaimer says "You also agree not to alter the bot's code. "

Please choose an existing open source License so your intentions are more clear. MIT or BSD are good options that are similar to the language described in your license.

**Comment by Hunchmun** [comment]
Apologies for this issue, for now, please refer to the first argument you referenced as this is more accurate.

The licensing has been written by different people at different times, I will Look into making this more clear and concise tommorrow,

Have a nice day

**Comment by nthitz** [comment]
thanks, I figured it's just an oversight but thought it should be mentioned

**Comment by Hunchmun** [comment]
You should find it updated more to your liking
