### ISSUE TITLE
Voteskip cannot be turned on with !togglevoteskip

### ISSUE THREAD

**Issue by MCzeKrakan** [Yemasthui/basicBot#45]
Hi guys, please take a look at line 1772 of Bots code. https://github.com/Yemasthui/basicBot/blob/master/basicBot.js#L1772 There should be voteSkip instead of motdEnabled. Hope i am right. Thanks, and keep up the good work, its great Bot.

**Comment by Benzi** [comment]
Sorry for being late to this.. I can't see where there seem to be an issue here. I presume the error might have been fixed.
