### ISSUE TITLE
Chat on slow mode

### ISSUE THREAD

**Issue by rogama25** [Yemasthui/basicBot#60]
I think that sometimes when you run the bot the chat turns on slow mode. Is this a bug?

When I type some command, this appears in the chat --The chat is on slow mode. Try again on 9 seconds--

**Comment by xSidewinderx** [comment]
Slow mode has nothing to do with running the bot.

**Comment by Hunchmun** [comment]
Hi, I'm Henchman, a Brand Ambassador for plug.dj

Plug.dj has employed certain rate limiting techniques, to prevent spam, and other malicious intent, such as DDoS. 

BasicBot at current does not rate limit it's messages, as they are generally event driven, but sometimes these, and the other messages that are driven by intervals can be sent at the same, or similiar time periods. The slow chat you are seeing is the default response to messages being blocked, or not processed by the server, however it is possible that it could be blocked by the client side API to prevent harm to the server, both resulting in the same outcome.

It is possible that basicBot could include a rate limiting and queueing system for messages in the future, but I cannot tell you whether the other developers have planned it in the roadmap.

Hopefully this answers your question, it is not a bug of basicBot, but a part of the rate limiting system put in place by plug.dj.
