### ISSUE TITLE
!gif

### ISSUE THREAD

**Issue by hotchoc26** [Yemasthui/basicBot#61]
!gif seems to have stopped working for me, on multiple accounts and refreshing/restarting will not work.

**Comment by motelbible** [comment]
Yea, stopped working! :'(
It'll hopefully be fixed soon

**Comment by xSidewinderx** [comment]
This has been fixed.

**Comment by Benzi** [comment]
@hotchoc26 Yeah, Giphy did some unannounced changes. It has since been fixed though.
