### ISSUE TITLE
[Bug] Welcome Users Firefox

### ISSUE THREAD

**Issue by choccat** [Yemasthui/basicBot#64]
Using your latest update, the bot no longer welcomes users if it is run via firefox. This works in previous updates but not this one. 
Thanks,

**Comment by motelbible** [comment]
I'm not in charge of basicBot. I'm the official pt-br translator for basicBot. If you ever need help with setting basicBot, join us > [gitter](https://gitter.im/Yemasthui/basicBot)

**Comment by Fuhlanjeez** [comment]
Yep, seems to not work in firefox :c

**Comment by Benzi** [comment]
@choccat is this still an issue? If so, could you elaborate?

**Comment by choccat** [comment]
Seems to work with the latest update. @Benzi

**Comment by Benzi** [comment]
Great.
