### ISSUE TITLE
[Firefox] Syntax error when code is entered into the console

### ISSUE THREAD

**Issue by Ryan123777** [Yemasthui/basicBot#66]
When you use 
`javascript:(function(){$.getScript('https://rawgit.com/Yemasthui/basicBot-customization/master/extension.js');})();` in Firefox, it returns a `SyntaxError: missing ] in index expression`

This also happens when you do alternative and post the raw code from `https://rawgit.com/Yemasthui/basicBot-customization/master/extension.js`

**Comment by Hunchmun** [comment]
Can you give a line number? A complete screenshot of the stack trace?

**Comment by Ryan123777** [comment]
Strangely enough, I'm not getting this error anymore. Also, where the line number should be, it just says `extension.js`
