### ISSUE TITLE
Randomly removing people from waitlist

### ISSUE THREAD

**Issue by hoihoi661** [Yemasthui/basicBot#70]
Bot seems to be randomly removing people from the wailist, no afk warning message or anything. It seems to just be doing it with a specific set of people, anyone else bumped into this problem?

**Comment by hoihoi661** [comment]
Just took a look at code, my bad, it pretty much can't be basic bot as it's showing 0 messages, I'll take this to whoever made the custom bot for us.

**Comment by Hunchmun** [comment]
Good to know its not a problem with basic bot, please let me know if theres anything we can help with!
