### ISSUE TITLE
Is there any way to disable the song summary at the end of each song?

### ISSUE THREAD

**Issue by o355** [Yemasthui/basicBot#79]
I would like to know if there is any way to disable this after each song plays (through a command would be prefered):
Song name - 1W/0G/0M

**Comment by xSidewinderx** [comment]
Type !songstats

**Comment by Hunchmun** [comment]
@o355 has this solved your problem?

**Comment by Benzi** [comment]
I'll close this for now. You can re-open it if you need more help.
