### ISSUE TITLE
Uncaught TypeError

### ISSUE THREAD

**Issue by 7bf70ec5** [Yemasthui/basicBot#80]
I keep on getting this when I run the latest basicBot or make a copy of basicBot and edit it.

Uncaught TypeError: Cannot read property 'time' of null
Uncaught TypeError: Cannot read property 'name' of null

**Comment by Hunchmun** [comment]
Can't reproduce with v2.8.9, please provide more info

**Comment by 7bf70ec5** [comment]
Developers have fixed it.
