### ISSUE TITLE
feature request: make autoSkip customizable

### ISSUE THREAD

**Issue by jgm106** [Yemasthui/basicBot#81]
I'd like to set autoskip to true by default.

**Comment by xSidewinderx** [comment]
You should just be able to toggle it on, then leave it. The bot should save the settings, unless your clear you cache, cookies.

**Comment by Benzi** [comment]
@jgm106 you can fork [this](https://github.com/Yemasthui/basicBot-customization) and set `autoSkip` to `true` in the `extension.js`.

**Comment by jgm106** [comment]
@Benzi I tried that and it didn't work. It looks like autoSkip is basicBot.room.autoskip and not basicBot.settings.autoskip. I didn't want to munge our customization stuff to far off the main repo.

**Comment by Benzi** [comment]
Oh I see! Sorry about that. This https://github.com/Yemasthui/basicBot/commit/a50a846a774208e077248a0aa0c34af9413e9067 should let you set `autoskip` to `true` by default under the bot settings.
